"""Internal engine contract for in-memory record tables."""

from __future__ import annotations

from collections.abc import Callable, Iterable, Mapping
from typing import Any, Protocol

from ..records import CacheRecord


class MemoryEngine(Protocol):
    def get(self, key: object) -> CacheRecord[Any] | None: ...

    def set(self, key: object, record: CacheRecord[Any]) -> int: ...

    def delete(self, key: object) -> bool: ...

    def contains(self, key: object) -> bool: ...

    def clear(self) -> None: ...

    def get_many(self, keys: Iterable[object]) -> dict[object, CacheRecord[Any]]: ...

    def set_many(self, records: Mapping[object, CacheRecord[Any]]) -> int: ...

    def delete_many(self, keys: Iterable[object]) -> int: ...

    def prune(self, predicate: Callable[[CacheRecord[Any]], bool]) -> int: ...

    def __len__(self) -> int: ...
